name: release

permissions:
  contents: write

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Build release
        run: cargo build --release
      - name: Collect artifact (non-Windows)
        if: runner.os != 'Windows'
        run: |
          mkdir -p dist
          cp target/release/yr-weather-mcp dist/yr-weather-mcp-${{ runner.os }}
      - name: Collect artifact (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force -Path dist | Out-Null
          Copy-Item target/release/yr-weather-mcp.exe dist/yr-weather-mcp-${{ runner.os }}.exe
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: yr-weather-mcp-${{ runner.os }}
          path: dist/*

  create-release:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v4
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            artifacts/**/yr-weather-mcp-*
